name: "Build and Push Dev Container image"
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and push Dev Container image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check tag is on master branch
        run: git fetch origin master && git rev-list origin/master -- | grep -q ${{ github.sha }}
      
      - name: Get tag name
        id: get_tag_name
        run: echo "tag=$(echo "${{ github.ref }}" | grep -oP 'refs/tags/\K(.+)')" >> $GITHUB_OUTPUT

      - name: Build
        uses: devcontainers/ci@v0.2.1900000228
        with:
          imageName: ghcr.io/adam-jacobus/devcontainer-reach
          cacheFrom: ghcr.io/adam-jacobus/devcontainer-reach
          imageTag: ${{ steps.get_tag_name.outputs.tag }}
          runCmd: 'true'


